In [7]:
import requests
from bs4 import BeautifulSoup

In [2]:
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

url = "https://www.terra.com.br/esportes/futebol/brasileiro-serie-a/tabela/"

In [4]:
page = requests.get(url, headers=headers)

In [18]:
soup = BeautifulSoup(page.content, "html.parser")

In [11]:
#print(soup.prettify())

In [19]:
tables = soup.find_all("tbody")

In [23]:
data = []
list_tr = tables[0].find_all("tr")
for tr in list_tr:
    team = {}
    list_td = tr.find_all("td")
    team['position'] = list_td[0].text
    team['name'] = list_td[2].a.attrs['title']
    team['points'] = list_td[4].text
    data.append(team)

In [24]:
import pandas as pd
df  = pd.DataFrame(data)
df

   position                 name points
0         1               Santos      7
1         2          Atlético-MG      7
2         3          Corinthians      6
3         4               Cuiabá      6
4         5        Internacional      6
5         6                 Avaí      6
6         7           Bragantino      5
7         8            Palmeiras      5
8         9             Flamengo      5
9        10             Coritiba      4
10       11            São Paulo      4
11       12             Botafogo      4
12       13           Fluminense      4
13       14           América-MG      3
14       15                Ceará      3
15       16         Athletico-PR      3
16       17  Atlético Goianiense      2
17       18                Goiás      1
18       19            Juventude      1
19       20            Fortaleza      0